<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Branch;
use App\Models\Company;
use App\Models\dc;
use App\Models\ProdGroup;
use App\Models\Region;
use App\Models\RouteType;
use App\Models\SalesReg;
use App\Models\Scinvoice;
use App\Models\Warehouse;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Database\Factories\ScinvoiceFactory;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Scinvoice::factory(10)->create();

        Branch::truncate();
        $branches = [
            [
                'branch_code' => 1,
                'branch_appr' => 'CAI',
                'branch_name' => 'CAIRO',
                'to_sla'      => '@To_Sla_Cai',
                'branch_seq'  => 1,
            ], [
                'branch_code' => 2,
                'branch_appr' => 'ALX',
                'branch_name' => 'ALEX',
                'to_sla'      => '@TO_SLA_ALX',
                'branch_seq'  => 2,
            ], [
                'branch_code' => 3,
                'branch_appr' => 'MNS',
                'branch_name' => 'DELTA (B)',
                'to_sla'      => '@to_sla_man',
                'branch_seq'  => 4,
            ], [
                'branch_code' => 4,
                'branch_appr' => 'ISM',
                'branch_name' => 'CANAL',
                'to_sla'      => '@to_sla_ism',
                'branch_seq'  => 5,
            ], [
                'branch_code' => 5,
                'branch_appr' => 'AST',
                'branch_name' => 'MIDDLE EGYPT',
                'to_sla'      => '@to_sla_ast',
                'branch_seq'  => 6,
            ], [
                'branch_code' => 6,
                'branch_appr' => 'TNT',
                'branch_name' => 'DELTA (A)',
                'to_sla'      => '@to_sla_tan',
                'branch_seq'  => 3,
            ], [
                'branch_code' => 7,
                'branch_appr' => 'UPP',
                'branch_name' => 'UPPER EGYPT',
                'to_sla'      => '@to_sla_upp',
                'branch_seq'  => 7,
            ]
        ];

        Branch::insert($branches);

        Company::truncate();
        $company = [
            [
                'company_id'   => 100,
                'company_name' => 'FINE',
                'company_flag' => 1,
                'company_seq'  => 6,
            ],
            [
                'company_id'   => 15,
                'company_name' => 'BAT_GLO',
                'company_flag' => 1,
                'company_seq'  => 5,
            ],
            [
                'company_id'   => 14,
                'company_name' => 'BIC',
                'company_flag' => 1,
                'company_seq'  => 3,
            ],
            [
                'company_id'   => 13,
                'company_name' => 'ITG_loose_tobacoo',
                'company_flag' => 1,
                'company_seq'  => 4,
            ],
            [
                'company_id'   => 12,
                'company_name' => 'JTI',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 11,
                'company_name' => 'Assal',
                'company_flag' => 0,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 10,
                'company_name' => 'Hayat',
                'company_flag' => 0,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 9,
                'company_name' => 'Mazaya',
                'company_flag' => 0,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 8,
                'company_name' => 'ITG',
                'company_flag' => 0,
                'company_seq'  => 2,
            ],
            [
                'company_id'   => 7,
                'company_name' => 'VSPM',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 6,
                'company_name' => 'Water',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 5,
                'company_name' => 'BAT',
                'company_flag' => 1,
                'company_seq'  => 1,
            ],
            [
                'company_id'   => 4,
                'company_name' => 'EASTERN',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 3,
                'company_name' => 'FORUM',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 2,
                'company_name' => 'PM',
                'company_flag' => 1,
                'company_seq'  => null,
            ],
            [
                'company_id'   => 1,
                'company_name' => 'FOOD WS',
                'company_flag' => 1,
                'company_seq'  => null,
            ]
        ];

        Company::insert($company);

        Region::truncate();
        $start  = new Carbon('2018-10-04 15:00:03');
        $startEnd  = new Carbon('2018-10-04');
        $region = [
            [
                'reg_id'         => 7,
                'reg_code'       => null,
                'name'           => 'الدلتا',
                'name_e'         => 'Delta (B)',
                'entry_date'     =>  new Carbon('08/25/1999 14:54:05'),
                'update_date'    => new Carbon('03/16/2003'),
                'reg_census_code' => 03,
                'reg_name'       => 'Delta',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 3,
            ],
            [
                'reg_id'         => 5,
                'reg_code'       => null,
                'name'           => 'الاسكندرية',
                'name_e'         => 'ALEXANDRIA',
                'entry_date'     =>  new Carbon('08/01/1999 15:23:22'),
                'update_date'    => new Carbon('03/24/2002'),
                'reg_census_code' => 02,
                'reg_name'       => null,
                'action'         => 'I',
                'trans_flag'     => 1,
                'branch_code'    => 6,
            ],
            [
                'reg_id'         => 7,
                'reg_code'       => 03,
                'name'           => 'الدلتا',
                'name_e'         => 'DELTA (A)',
                'entry_date'     =>  new Carbon('08/25/1999 14:54:05'),
                'update_date'    => new Carbon('04/03/2002'),
                'reg_census_code' => 03,
                'reg_name'       => null,
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 6,
            ],
            [
                'reg_id'         => 5,
                'reg_code'       => null,
                'name'           => 'الاسكندرية',
                'name_e'         => 'ALEXANDRIA',
                'entry_date'     =>  new Carbon('08/01/1999 15:23:22'),
                'update_date'    => new Carbon('03/24/2002'),
                'reg_census_code' => 02,
                'reg_name'       => null,
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 2,
            ],
            [
                'reg_id'         => 6,
                'reg_code'       => null,
                'name'           => 'دلتا - الاسكندرية',
                'name_e'         => 'DELTA (A)',
                'entry_date'     =>  new Carbon('08/01/1999 15:23:22'),
                'update_date'    => new Carbon('03/24/2002'),
                'reg_census_code' => 02,
                'reg_name'       => null,
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 2,
            ],
            [
                'reg_id'         => 6,
                'reg_code'       => null,
                'name'           => 'القناة',
                'name_e'         => 'CANAL',
                'entry_date'     =>  new Carbon('07/24/1999 12:40:17'),
                'update_date'    => new Carbon('03/24/2002'),
                'reg_census_code' => 04,
                'reg_name'       => 'Canal',
                'action'         => 'U',
                'trans_flag'     => 1,
                'branch_code'    => 4,
            ],
            [
                'reg_id'         => 7,
                'reg_code'       => 03,
                'name'           => 'الدلتا',
                'name_e'         => 'ALEX',
                'entry_date'     =>  new Carbon('08/25/1999 14:54:05'),
                'update_date'    => new Carbon('04/03/2002'),
                'reg_census_code' => 03,
                'reg_name'       => 'الدلتا',
                'action'         => 'U',
                'trans_flag'     => 1,
                'branch_code'    => 2,
            ],
            [
                'reg_id'         => 9,
                'reg_code'       => null,
                'name'           => 'صعيد مصر',
                'name_e'         => 'UPPER EGYPT',
                'entry_date'     =>  new Carbon('07/24/1999 12:40:17'),
                'update_date'    => new Carbon('04/30/2002'),
                'reg_census_code' => 06,
                'reg_name'       => 'UPPER',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 7,
            ],
            [
                'reg_id'         => 1,
                'reg_code'       => null,
                'name'           => 'القاهرة',
                'name_e'         => 'CAIRO',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => null,
                'reg_census_code' => null,
                'reg_name'       => 'القاهرة',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 7,
            ],
            [
                'reg_id'         => 8,
                'reg_code'       => null,
                'name'           => 'مصر الوسطى',
                'name_e'         => 'MIDDLE EGYPT',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => new Carbon('04/09/2002'),
                'reg_census_code' => 05,
                'reg_name'       => 'مصر الوسطى',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 7,
            ],
            [
                'reg_id'         => 1,
                'reg_code'       => 1,
                'name'           => 'القاهرة',
                'name_e'         => 'CAIRO',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => new Carbon('07/07/2003'),
                'reg_census_code' => 01,
                'reg_name'       => 'Cairo',
                'action'         => 'U',
                'trans_flag'     => 1,
                'branch_code'    => 1,
            ],
            [
                'reg_id'         => 7,
                'reg_code'       => 7,
                'name'           => 'الدلتا',
                'name_e'         => 'DELTA (A)',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => new Carbon('07/07/2003'),
                'reg_census_code' => 03,
                'reg_name'       => 'DeltA',
                'action'         => 'U',
                'trans_flag'     => 1,
                'branch_code'    => 1,
            ],
            [
                'reg_id'         => 9,
                'reg_code'       => null,
                'name'           => 'صعيد مصر',
                'name_e'         => 'UPPER EGYPT',
                'entry_date'     =>  new Carbon('01/18/2004 12:40:17'),
                'update_date'    => new Carbon('01/01/2004'),
                'reg_census_code' => 06,
                'reg_name'       => 'صعيد مصر',
                'action'         => 'I',
                'trans_flag'     => 1,
                'branch_code'    => 1,
            ],
            [
                'reg_id'         => 1,
                'reg_code'       => null,
                'name'           => 'مصر الوسطى',
                'name_e'         => 'CAIRO',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => null,
                'reg_census_code' => null,
                'reg_name'       => 'القاهرة',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 5,
            ],
            [
                'reg_id'         => 9,
                'reg_code'       => null,
                'name'           => 'صعيد مصر',
                'name_e'         => 'UPPER EGYPT',
                'entry_date'     =>  new Carbon('01/18/2004 12:40:17'),
                'update_date'    => new Carbon('01/01/2004'),
                'reg_census_code' => 06,
                'reg_name'       => 'صعيد مصر',
                'action'         => 'I',
                'trans_flag'     => 1,
                'branch_code'    => 5,
            ],
            [
                'reg_id'         => 8,
                'reg_code'       => null,
                'name'           => 'مصر الوسطى',
                'name_e'         => 'MIDDLE EGYPT',
                'entry_date'     =>  new Carbon('08/01/1999 14:58:17'),
                'update_date'    => new Carbon('04/09/2002'),
                'reg_census_code' => 05,
                'reg_name'       => 'مصر الوسطى',
                'action'         => 'D',
                'trans_flag'     => 1,
                'branch_code'    => 5,
            ],

        ];

        Region::insert($region);

        SalesReg::truncate();

        $SalesReg = [
            [
                'sales_reg_id'  => 3,
                'sales_reg_code' => null,
                'Name'          => 'DELTA (B)',
                'entry_date' => new Carbon('08/25/1999 14:54:09'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => 'DELTA (B)',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'sales_reg_id'  => 6,
                'sales_reg_code' => null,
                'Name'          => 'DELTA (A)',
                'entry_date' => new Carbon('08/01/1999 14:58:21'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'sales_reg_id'  => 2,
                'sales_reg_code' => null,
                'Name'          => 'ALEX',
                'entry_date' => new Carbon('08/01/1999 15:23:24'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => null,
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'sales_reg_id'  => 4,
                'sales_reg_code' => null,
                'Name'          => 'CANAL',
                'entry_date' => new Carbon('07/24/1999 12:40:37'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => 'CANAL',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 4,
            ],
            [
                'sales_reg_id'  => 7,
                'sales_reg_code' => null,
                'Name'          => 'UPPER EGYPT',
                'entry_date' => new Carbon('07/24/1999 12:40:37'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'sales_reg_id'  => 1,
                'sales_reg_code' => null,
                'Name'          => 'CAIRO',
                'entry_date' => new Carbon('08/01/1999 14:58:21'),
                'update_date' => new Carbon('01/01/9999'),
                'aname' => 'CAIRO',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'sales_reg_id'  => 5,
                'sales_reg_code' => null,
                'Name'          => 'MIDDLE EGYPT',
                'entry_date' => new Carbon('08/01/1999 14:58:21'),
                'update_date' => new Carbon('01/01/2099'),
                'aname' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
        ];

        SalesReg::insert($SalesReg);

        dc::truncate();

        $dc = [
            [
                'DC_ID' => '60000',
                'DC_Code' => null,
                'Name' => 'ZAKAZIK',
                'sales_reg_id' => 3,
                'entry_date' => new Carbon('01/23/2000 14:57:31'),
                'update_date' => null,
                'DESC_DC' => 'SHARKIA',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '11',
                'DC_Code' => null,
                'Name' => 'MANSOURA',
                'sales_reg_id' => 3,
                'entry_date' => new Carbon('08/25/1999 14:53:31'),
                'update_date' => null,
                'DESC_DC' => 'MANSOURA',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '12',
                'DC_Code' => null,
                'Name' => 'DAMIETTA',
                'sales_reg_id' => 3,
                'entry_date' => new Carbon('08/25/1999 14:53:31'),
                'update_date' => new Carbon('04/13/2003'),
                'DESC_DC' => 'DAMIETTA',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '101',
                'DC_Code' => null,
                'Name' => 'Damanhour',
                'sales_reg_id' => 6,
                'entry_date' => new Carbon('07/13/2021'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 6,
            ],
            [
                'DC_ID' => '501',
                'DC_Code' => null,
                'Name' => 'SOHAG_fine',
                'sales_reg_id' => 5,
                'entry_date' => new Carbon('11/01/2021 20:40:22'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
            [
                'DC_ID' => '9',
                'DC_Code' => null,
                'Name' => 'TANTA',
                'sales_reg_id' => 6,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 6,
            ],
            [
                'DC_ID' => '7',
                'DC_Code' => null,
                'Name' => 'MANDARA',
                'sales_reg_id' => 2,
                'entry_date' => new Carbon('08/01/1999 15:22:42'),
                'update_date' => new Carbon('09/05/2000'),
                'DESC_DC' => 'HAGAR ELNAWATEYA',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'DC_ID' => '8',
                'DC_Code' => null,
                'Name' => 'KABBARY',
                'sales_reg_id' => 2,
                'entry_date' => new Carbon('08/01/1999 15:22:42'),
                'update_date' => null,
                'DESC_DC' => 'KABBARY',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'DC_ID' => '100',
                'DC_Code' => null,
                'Name' => 'HAGAR EL NAWATIA',
                'sales_reg_id' => 2,
                'entry_date' => new Carbon('06/25/2002 17:34:39'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'DC_ID' => '13',
                'DC_Code' => null,
                'Name' => 'ISMAILIA',
                'sales_reg_id' => 4,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'Ismailia',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 4,
            ],
            [
                'DC_ID' => '18',
                'DC_Code' => null,
                'Name' => 'SUEZ',
                'sales_reg_id' => 4,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'suez',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 4,
            ],
            [
                'DC_ID' => '22',
                'DC_Code' => null,
                'Name' => 'SHARM EL SHEIKH',
                'sales_reg_id' => 4,
                'entry_date' => new Carbon('07/06/2000 16:40:06'),
                'update_date' => null,
                'DESC_DC' => 'sharm',
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 4,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '300',
                'DC_Code' => null,
                'Name' => 'Abourawah',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('04/01/2020 8:43:30'),
                'update_date' => null,
                'DESC_DC' => 'Abourawah',
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '102',
                'DC_Code' => null,
                'Name' => 'october',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('07/31/2021 20:29:29'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 4,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 6,
            ],
            [
                'DC_ID' => '99',
                'DC_Code' => null,
                'Name' => 'Dataentry',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('11/30/2021 17:53:04'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'DC_ID' => '103',
                'DC_Code' => null,
                'Name' => 'Monofia',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('07/31/2021 20:30:39'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 6,
            ],
            [
                'DC_ID' => '104',
                'DC_Code' => null,
                'Name' => 'Zakazik',
                'sales_reg_id' => 3,
                'entry_date' => new Carbon('07/31/2021 20:30:39'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '400',
                'DC_Code' => null,
                'Name' => 'Kabary',
                'sales_reg_id' => 2,
                'entry_date' => new Carbon('05/17/2001 13:44:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 2,
            ],
            [
                'DC_ID' => '500',
                'DC_Code' => null,
                'Name' => 'Cairo_fine',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('09/30/2021 20:03:40'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'I',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '19',
                'DC_Code' => null,
                'Name' => 'ASWAN',
                'sales_reg_id' => 7,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'DC_ID' => '16',
                'DC_Code' => null,
                'Name' => 'LUXOR',
                'sales_reg_id' => 7,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'DC_ID' => '17',
                'DC_Code' => null,
                'Name' => 'HURGHADA',
                'sales_reg_id' => 7,
                'entry_date' => new Carbon('08/01/1999 14:35:11 '),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'DC_ID' => '1',
                'DC_Code' => null,
                'Name' => 'MOHANDESSINE',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'MOOOOO',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 7,
            ],
            [
                'DC_ID' => '2',
                'DC_Code' => null,
                'Name' => 'MAADI',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'MAADI',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '3',
                'DC_Code' => null,
                'Name' => 'NASR CITY',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'FDS',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '4',
                'DC_Code' => null,
                'Name' => 'NAZLET EL SEMAN',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '5',
                'DC_Code' => null,
                'Name' => 'SHOUBRA',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '6',
                'DC_Code' => null,
                'Name' => 'SMOUHA',
                'sales_reg_id' => 2,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => 'SMOUHA',
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '23',
                'DC_Code' => null,
                'Name' => 'ZAHRAA EL MAADI',
                'sales_reg_id' => 1,
                'entry_date' => new Carbon('07/08/2002 12:31:48'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 1,
            ],
            [
                'DC_ID' => '10',
                'DC_Code' => null,
                'Name' => 'ZAGAZIG',
                'sales_reg_id' => 3,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'D',
                'trans_flag' => 1,
                'branch_code' => 3,
            ],
            [
                'DC_ID' => '14',
                'DC_Code' => null,
                'Name' => 'MENIA',
                'sales_reg_id' => 5,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
            [
                'DC_ID' => '15',
                'DC_Code' => null,
                'Name' => 'ASSIOUT',
                'sales_reg_id' => 5,
                'entry_date' => new Carbon('08/01/1999 14:35:11'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
            [
                'DC_ID' => '21',
                'DC_Code' => null,
                'Name' => 'BANY SWEF',
                'sales_reg_id' => 5,
                'entry_date' => new Carbon('03/07/2000 8:37:40'),
                'update_date' => null,
                'DESC_DC' => null,
                'action' => 'U',
                'trans_flag' => 1,
                'branch_code' => 5,
            ],
        ];

        dc::insert($dc);

        Warehouse::truncate();

        $warehouse = [
            [
                'warehouse_id'=>15,
                'warehouse_name'=>'Abourawah- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>3950,
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>'Abourawah',
                'dc_id_sfis'=>300,
                'branch_code'=>1,
                'to_sla_LNK'=>null,
                'sales_office'=>23,
            ],
            [
                'warehouse_id'=>17,
                'warehouse_name'=>'Damanhour Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'T200',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>'Damanhour',
                'dc_id_sfis'=>101,
                'branch_code'=>6,
                'to_sla_LNK'=>null,
                'sales_office'=>101,
            ],
            [
                'warehouse_id'=>18,
                'warehouse_name'=>'6-october  Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'3200',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>'6-october',
                'dc_id_sfis'=>102,
                'branch_code'=>1,
                'to_sla_LNK'=>null,
                'sales_office'=>301,
            ],
            [
                'warehouse_id'=>19,
                'warehouse_name'=>'monofia  Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'T300',
                'warehouse_desc'=>null,
                'warehouse_address'=>'monofia',
                'zip_code'=>null,
                'warehouse_city'=>'monofia',
                'dc_id_sfis'=>103,
                'branch_code'=>6,
                'to_sla_LNK'=>null,
                'sales_office'=>9,
            ],
            [
                'warehouse_id'=>20,
                'warehouse_name'=>'Zakazik-new',
                'def_warehouse'=>0,
                'warehouse_code'=>'3900',
                'warehouse_desc'=>null,
                'warehouse_address'=>'monofia',
                'zip_code'=>44519,
                'warehouse_city'=>'Sharkeya',
                'dc_id_sfis'=>104,
                'branch_code'=>3,
                'to_sla_LNK'=>'@TO_SLA_MAN',
                'sales_office'=>104,
            ],
            [
                'warehouse_id'=>21,
                'warehouse_name'=>'Kabary Warehouse (Alex)',
                'def_warehouse'=>0,
                'warehouse_code'=>'T400',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>null,
                'dc_id_sfis'=>400,
                'branch_code'=>2,
                'to_sla_LNK'=>null,
                'sales_office'=>302,
            ],
            [
                'warehouse_id'=>1,
                'warehouse_name'=>'Mansoura Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'MT1',
                'warehouse_desc'=>'31',
                'warehouse_address'=>'Ahmed abdel aziz Street, Taksim samya el gamal, Asfour Building ',
                'zip_code'=>35111,
                'warehouse_city'=>'Mansoura',
                'dc_id_sfis'=>11,
                'branch_code'=>3,
                'to_sla_LNK'=>'@TO_SLA_MAN',
                'sales_office'=>11,
            ],
            [
                'warehouse_id'=>3,
                'warehouse_name'=>'Sharm ELSheikh- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'ST1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'Sharm El Sheikh',
                'zip_code'=>46619,
                'warehouse_city'=>'Sharm El Sheikh',
                'dc_id_sfis'=>22,
                'branch_code'=>4,
                'to_sla_LNK'=>'@TO_SLA_ISM',
                'sales_office'=>22,
            ],
            [
                'warehouse_id'=>4,
                'warehouse_name'=>'Ismaileya- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'IT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'El makhbaz el aly , El sheikh zayed district , Part no 12, El Yasmen Building',
                'zip_code'=>41112,
                'warehouse_city'=>'Ismailia',
                'dc_id_sfis'=>13,
                'branch_code'=>4,
                'to_sla_LNK'=>'@TO_SLA_ISM	',
                'sales_office'=>13,
            ],
            [
                'warehouse_id'=>5,
                'warehouse_name'=>'Luxor- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'LT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'El mostashfa el dawly Street , Amr wahba Building , El Fayrouz District',
                'zip_code'=>85951,
                'warehouse_city'=>'Luxor',
                'dc_id_sfis'=>16,
                'branch_code'=>7,
                'to_sla_LNK'=>'@TO_SLA_UPP',
                'sales_office'=>16,
            ],
            [
                'warehouse_id'=>6,
                'warehouse_name'=>'Asyout- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'AT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'El namees Street  , El petrol district , Dr Ahmed el tayeb Building',
                'zip_code'=>71511,
                'warehouse_city'=>'Asyout',
                'dc_id_sfis'=>15,
                'branch_code'=>5,
                'to_sla_LNK'=>'@TO_SLA_AST',
                'sales_office'=>15,
            ],
            [
                'warehouse_id'=>7,
                'warehouse_name'=>'Menya- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'ET1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'71 mohamed el sab3 Street , Shalaby district , Ahmed mohamed gamal Building',
                'zip_code'=>61111,
                'warehouse_city'=>'Menya',
                'dc_id_sfis'=>14,
                'branch_code'=>5,
                'to_sla_LNK'=>'@TO_SLA_AST',
                'sales_office'=>14,
            ],
            [
                'warehouse_id'=>8,
                'warehouse_name'=>'Damietta- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'DT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'Emtedad kornish el nile Street, Mohamed Basal Building',
                'zip_code'=>34111,
                'warehouse_city'=>'Damietta',
                'dc_id_sfis'=>12,
                'branch_code'=>1,
                'to_sla_LNK'=>'@TO_SLA_MAN',
                'sales_office'=>12,
            ],
            [
                'warehouse_id'=>9,
                'warehouse_name'=>'Tanta- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'TT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'26 Hasan Radwan Street, From El Bahr Street',
                'zip_code'=>31111,
                'warehouse_city'=>'Tanta',
                'dc_id_sfis'=>9,
                'branch_code'=>6,
                'to_sla_LNK'=>'@TO_SLA_TAN',
                'sales_office'=>9,
            ],
            [
                'warehouse_id'=>10,
                'warehouse_name'=>'Hagar ELNawateya- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'HT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'Hagar El Nawateya District , kanal el Mahmodeya Street',
                'zip_code'=>21131,
                'warehouse_city'=>'Alexandria',
                'dc_id_sfis'=>100,
                'branch_code'=>2,
                'to_sla_LNK'=>'@TO_SLA_ALX',
                'sales_office'=>2,
            ],
            [
                'warehouse_id'=>11,
                'warehouse_name'=>'Zahraa ELmaadi- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'ZT1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'Industry Zone, Zahraa el Maadi , Division 6 & 5 from Part 98 to 108',
                'zip_code'=>11341,
                'warehouse_city'=>'Cairo',
                'dc_id_sfis'=>23,
                'branch_code'=>1,
                'to_sla_LNK'=>'@TO_SLA_CAI',
                'sales_office'=>23,
            ],
            [
                'warehouse_id'=>12,
                'warehouse_name'=>'Aswan- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'AN1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'Berket El Damas , Khodary Building',
                'zip_code'=>81718,
                'warehouse_city'=>'Aswan',
                'dc_id_sfis'=>19,
                'branch_code'=>7,
                'to_sla_LNK'=>'@TO_SLA_UPP',
                'sales_office'=>19,
            ],
            [
                'warehouse_id'=>2,
                'warehouse_name'=>'Beni Suef- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'BS1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'31 El hay el togary , Beni Suef el Gedida',
                'zip_code'=>61111,
                'warehouse_city'=>'Bane swif',
                'dc_id_sfis'=>21,
                'branch_code'=>5,
                'to_sla_LNK'=>'@TO_SLA_AST',
                'sales_office'=>21,
            ],
            [
                'warehouse_id'=>13,
                'warehouse_name'=>'Zakazik- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'ZZ1',
                'warehouse_desc'=>null,
                'warehouse_address'=>'El Salam District , 13 Masraf Akwa Street, Near Salah Salem Hospital , El Hag Attia Abouzeid Building',
                'zip_code'=>44519,
                'warehouse_city'=>'Sharkeya',
                'dc_id_sfis'=>60000,
                'branch_code'=>3,
                'to_sla_LNK'=>'@TO_SLA_MAN',
                'sales_office'=>104,
            ],
            [
                'warehouse_id'=>16,
                'warehouse_name'=>'Hurghada- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'3550',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>44519,
                'warehouse_city'=>'Hurghada',
                'dc_id_sfis'=>17,
                'branch_code'=>7,
                'to_sla_LNK'=>null,
                'sales_office'=>17,
            ],
            [
                'warehouse_id'=>14,
                'warehouse_name'=>'ELSAHEL- Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'T100',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>'ELSAHEL',
                'dc_id_sfis'=>200,
                'branch_code'=>2,
                'to_sla_LNK'=>null,
                'sales_office'=>200,
            ],
            [
                'warehouse_id'=>22,
                'warehouse_name'=>'Sohag Warehouse',
                'def_warehouse'=>0,
                'warehouse_code'=>'3400',
                'warehouse_desc'=>null,
                'warehouse_address'=>null,
                'zip_code'=>null,
                'warehouse_city'=>'ELSAHEL',
                'dc_id_sfis'=>501,
                'branch_code'=>5,
                'to_sla_LNK'=>null,
                'sales_office'=>303,
            ],
            ];

            Warehouse::insert($warehouse);

            RouteType::truncate();

            $routeType=[
                [
                    'route_type_id'=>81,
                    'route_type_code'=>'MER',
                    'name'=>'KA_MERCHANDISING_RT',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('12/17/2008'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>10,
                    'route_type_code'=>'SALES',
                    'name'=>'MINI MARKET',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('09/05/2021 16:20:24'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>6,
                    'route_type_code'=>'SALES',
                    'name'=>'SEMI WHOLESALE',
                    'UOM_Unit'=>1,
                    'channel_id'=>5,
                    'entry_date'=>new Carbon('11/22/2020 14:43:19'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>1,
                ],
                [
                    'route_type_id'=>20,
                    'route_type_code'=>'CE',
                    'name'=>'CE',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('05/24/2021'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>300,
                    'route_type_code'=>'SUPERVISOR',
                    'name'=>'Supervisor_RT',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('02/03/2022'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>16,
                    'route_type_code'=>'SALES',
                    'name'=>'TOP',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('06/02/2022 16:35:07'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>200,
                    'route_type_code'=>'TMR',
                    'name'=>'TMR',
                    'UOM_Unit'=>0,
                    'channel_id'=>69,
                    'entry_date'=>new Carbon('12/17/2008'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>100000,
                    'route_type_code'=>'MER',
                    'name'=>'KA_ MERCHANDIZING',
                    'UOM_Unit'=>0,
                    'channel_id'=>48,
                    'entry_date'=>new Carbon('04/23/2009 17:14:50 '),
                    'update_date'=>new Carbon('04/23/2009'),
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>1,
                    'route_type_code'=>'SALES',
                    'name'=>'WHOLESALE',
                    'UOM_Unit'=>1,
                    'channel_id'=>1,
                    'entry_date'=>new Carbon('08/01/1999 14:58:18'),
                    'update_date'=>new Carbon('04/23/2009'),
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>2,
                    'route_type_code'=>'SALES',
                    'name'=>'DIRECT SALES',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('08/01/1999 14:58:18'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>3,
                    'route_type_code'=>'IND',
                    'name'=>'INDIRECT SALES',
                    'UOM_Unit'=>0,
                    'channel_id'=>66,
                    'entry_date'=>new Carbon('08/01/1999 14:58:18'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>4,
                    'route_type_code'=>'MER',
                    'name'=>'TRADE MARKITING	',
                    'UOM_Unit'=>1,
                    'channel_id'=>3,
                    'entry_date'=>new Carbon('08/01/1999 14:58:18'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>5,
                    'route_type_code'=>'SALES',
                    'name'=>'SUPERMARKET',
                    'UOM_Unit'=>1,
                    'channel_id'=>4,
                    'entry_date'=>new Carbon('08/01/1999 14:58:18'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>8,
                    'route_type_code'=>'MER',
                    'name'=>'VISITS RT',
                    'UOM_Unit'=>1,
                    'channel_id'=>8,
                    'entry_date'=>new Carbon('05/20/2003 13:07:43'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>8,
                    'route_type_code'=>'MER',
                    'name'=>'VISITS WS',
                    'UOM_Unit'=>1,
                    'channel_id'=>8,
                    'entry_date'=>new Carbon('05/20/2003 13:07:43'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>1,
                ],
                [
                    'route_type_id'=>30,
                    'route_type_code'=>'MER',
                    'name'=>'MERCHANDISING (old)',
                    'UOM_Unit'=>0,
                    'channel_id'=>28,
                    'entry_date'=>new Carbon('07/28/2003 14:26:57'),
                    'update_date'=>new Carbon('07/28/2003'),
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>71,
                    'route_type_code'=>'MER',
                    'name'=>'MERCHANDISING _ WS',
                    'UOM_Unit'=>1,
                    'channel_id'=>48,
                    'entry_date'=>new Carbon('04/06/2004 14:18:17'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>1,
                ],
                [
                    'route_type_id'=>70,
                    'route_type_code'=>'MER',
                    'name'=>'MERCHANDISING_RT',
                    'UOM_Unit'=>0,
                    'channel_id'=>48,
                    'entry_date'=>new Carbon('04/06/2004 14:18:17'),
                    'update_date'=>new Carbon('04/06/2004'),
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>11,
                    'route_type_code'=>'SALES',
                    'name'=>'PUSH TEAM',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('04/02/2008 17:27:19'),
                    'update_date'=>new Carbon('04/06/2004'),
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>80,
                    'route_type_code'=>'MER',
                    'name'=>'KA_MERCHANDISING _WS',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('12/17/2008'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>1,
                ],
                [
                    'route_type_id'=>12,
                    'route_type_code'=>'IND',
                    'name'=>'INDIRECT PUSH TEAM',
                    'UOM_Unit'=>0,
                    'channel_id'=>66,
                    'entry_date'=>new Carbon('02/28/2010 14:40:12'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>100,
                    'route_type_code'=>'ENG',
                    'name'=>'ENGAGEMENT TEAM',
                    'UOM_Unit'=>0,
                    'channel_id'=>67,
                    'entry_date'=>new Carbon('06/01/2011'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>13,
                    'route_type_code'=>'SALES',
                    'name'=>'ISD',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('04/10/2013 10:32:19'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>14,
                    'route_type_code'=>'SALES',
                    'name'=>'OOR',
                    'UOM_Unit'=>0,
                    'channel_id'=>2,
                    'entry_date'=>new Carbon('09/10/2014'),
                    'update_date'=>null,
                    'action'=>'U',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>15,
                    'route_type_code'=>'TMR',
                    'name'=>'TMR SALES',
                    'UOM_Unit'=>0,
                    'channel_id'=>69,
                    'entry_date'=>new Carbon('03/16/2020'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>72,
                    'route_type_code'=>'IND_MER',
                    'name'=>'Indirect MERCHANDISING _ WS',
                    'UOM_Unit'=>1,
                    'channel_id'=>48,
                    'entry_date'=>new Carbon('11/17/2021 15:05:54'),
                    'update_date'=>null,
                    'action'=>'I',
                    'trans_flag'=>1,
                    'UOM_id'=>2,
                ],
                [
                    'route_type_id'=>90000,
                    'route_type_code'=>'SALES',
                    'name'=>'NEW WHOLESALE',
                    'UOM_Unit'=>1,
                    'channel_id'=>1,
                    'entry_date'=>new Carbon('02/19/2008 11:01:01'),
                    'update_date'=>new Carbon('07/31/2008'),
                    'action'=>'I',
                    'trans_flag'=>0,
                    'UOM_id'=>1,
                ],
                ];

                RouteType::insert($routeType);

    }
}
